# Default values.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 2
repository: <DockerImagesRepositoryURL>
imagesTag: <DockerImagesTag>

global:
    DATABRICKS_WORKSPACE_URL: <DATABRICKS_WORKSPACE_URL>
    MLFLOW_SERVER_API_PREFIX: <MLFLOW_SERVER_API_PREFIX>
    APP_INSIGHTS_INSTRUMENTATION_KEY: <APP_INSIGHTS_INSTRUMENTATION_KEY>
    secret:
        DATABRICKS_AUTH_TOKEN: <DATABRICKS_AUTH_TOKEN>

prediction:
    name: prediction
    dockerImage: 
        name: prediction
    TRAINING_SERVICE_PORT: 80
    TRAINING_SERVICE_API_TRAIN_PATH: train
    TRAINING_REQUESTS_TIMEOUT: 10
    MLFLOW_MODELS_MAPPING: <MLFLOW_MODELS_MAPPING>
    
modelRunner:
    name: model-runner    
    dockerImage: 
        name: model-runner
    MLFLOW_SERVER_SEARCH_PATH: <MLFLOW_SERVER_SEARCH_PATH>
    MLFLOW_EXPERIMENT_ID: <MLFLOW_EXPERIMENT_ID>
    MLFLOW_REQUESTS_TIMEOUT: 10
    MODELS_RELATIVE_PATH: model
    MODEL_NAME: <MODEL_NAME>

training:
    name: training
    dockerImage: 
        name: training
    DATABRICKS_CLUSTER_ID: <DATABRICKS_CLUSTER_ID>
    DATABRICKS_RUN_TIMEOUT: 3600
    DATABRICKS_TYPE_MAPPING: <JSON represents ModelName => NotebookPath in Databricks> 
    #e.g: DATABRICKS_TYPE_MAPPING: '{"MODEL1":"/Shared/notebook1"}' 
    